// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcKmbQ_-4SWtsZNKvJELiq2fq3zdlJG8s',
    appId: '1:213593499729:web:2ef2a345d01d851e7e7070',
    messagingSenderId: '213593499729',
    projectId: 'demo3-31a30',
    authDomain: 'demo3-31a30.firebaseapp.com',
    storageBucket: 'demo3-31a30.firebasestorage.app',
    measurementId: 'G-8JBLZTXYFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA75Nbp_1-RzWg11JAE-i___JSsYjEgc2M',
    appId: '1:213593499729:android:c0eb3c6ff418ff247e7070',
    messagingSenderId: '213593499729',
    projectId: 'demo3-31a30',
    storageBucket: 'demo3-31a30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZYllB3S4Vby0hCQ-wXKr9Jcqf4V2zHJY',
    appId: '1:213593499729:ios:ca3b66891e5b8b827e7070',
    messagingSenderId: '213593499729',
    projectId: 'demo3-31a30',
    storageBucket: 'demo3-31a30.firebasestorage.app',
    iosBundleId: 'com.example.artsvault',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcKmbQ_-4SWtsZNKvJELiq2fq3zdlJG8s',
    appId: '1:213593499729:web:3f30120d1d08a4907e7070',
    messagingSenderId: '213593499729',
    projectId: 'demo3-31a30',
    authDomain: 'demo3-31a30.firebaseapp.com',
    storageBucket: 'demo3-31a30.firebasestorage.app',
    measurementId: 'G-BLXNWEVGXW',
  );
}
